### ISSUE TITLE
EavesDrop broken by 9.0.1

### ISSUE THREAD

**Issue by professionaltart** [domzae/EavesDrop#6] opened 2020-10-14 14:19 UTC
Curious if you're likely to get this working again for Shadowlands, @domzae ?  Currently reporting nothing from the combat log, but I'm not sure if that side is broken, or it's just the transparency of the window that maybe broke displaying it?

**Comment by vbhayden** [comment] 2020-10-14 14:26
I forked this awhile back with changes BFA but don't know if this repo is updated anymore.  Will reply here if I get things working for mine.

**Comment by domzae** [comment] 2020-10-14 16:17
I'm currently not playing WoW but will probably resub a bit before the expansion so will look at fixing it then - unless you're getting some lua errors you can share?

**Comment by rastuder** [comment] 2020-10-14 17:41
Can't currently login but one of the issues is regarding this:
```
"One of the major changes in 9.0 is a change to SetBackdrop. The TL/DR, on live, 100% of frames support backdrops, whether they are used or not. 1000s of frames between every addon and default UI, even frames that never see such as event frames have backdrops. UI team realized this is a serious performance issue. so effective in 9.0, no frames have backdrops unless the addon imports/inherits the backdrop template.
this means addons that aren’t importing them now throw nil errors with method “Setbackdrop”. This issue affects a large number of addons."
```
1x EavesDrop\EavesDropStats.lua:190: attempt to call method 'SetBackdropColor' (a nil value)
[string "@EavesDrop\EavesDropStats.lua"]:190: in function `SetupHistory'
[string "@EavesDrop\EavesDrop-v2.60.lua"]:381: in function `PerformDisplayOptions'
[string "@EavesDrop\EavesDrop-v2.60.lua"]:215: in function <EavesDrop\EavesDrop.lua:189>
[string "=[C]"]: ?
[string "@Ace3\AceAddon-3.0\AceAddon-3.0-13.lua"]:70: in function <Ace3\AceAddon-3.0\AceAddon-3.0.lua:65>
[string "@Ace3\AceAddon-3.0\AceAddon-3.0-13.lua"]:498: in function `InitializeAddon'
[string "@Ace3\AceAddon-3.0\AceAddon-3.0-13.lua"]:623: in function <Ace3\AceAddon-3.0\AceAddon-3.0.lua:615>

**Comment by Nazgul084** [comment] 2020-10-14 19:30
Possible fix:

https://us.forums.blizzard.com/en/wow/t/bunch-of-addons-failing-due-to-some-change-in-setbackdrop/676204/4

Edit: Greater discussion thread, here: https://www.wowinterface.com/forums/showthread.php?s=f4ef54abc625f6739512c200e62b1705&p=336634#post336634

**Comment by Nazgul084** [comment] 2020-10-14 20:56
Test Fix: Modify EavesDrop.xml to add the "BackdropTemplate" where necessary (lines *should* be accurate):
----------------------------------------------------------------------------------------
```
Line 9:	<Frame name="EavesDropEventTemplate" virtual="true" inherits="BackdropTemplate">
Line 113:	<Frame name="EavesDropHistoryEventTemplate" virtual="true" inherits="BackdropTemplate">
Line 205:	<Frame name="EavesDropFrame" enableMouse="true" movable="true" frameStrata="LOW" parent="UIParent" inherits="BackdropTemplate">
Line 609:	<Frame name="EavesDropHistoryFrame" enableMouse="true" movable="true" frameStrata="LOW" clampedToScreen="true" parent="UIParent" hidden="true" inherits="BackdropTemplate">
```

**Comment by Nazgul084** [comment] 2020-10-14 21:11
EavesDrop PlaySound error fix:

References to PlaySound (in EavesDrop.lua and EavesDrop.xml), code in this repository, need to have their format changed:

PlaySound("igChatScrollDown");  should be changed to  PlaySound(SOUNDKIT.IG_CHAT_SCROLL_DOWN);
PlaySound("igChatScrollUp");  should be changed to  PlaySound(SOUNDKIT.IG_CHAT_SCROLL_UP);
PlaySound("igMainMenuOptionCheckBoxOn");  should be changed to  PlaySound(SOUNDKIT.IG_MAINMENU_OPTION_CHECKBOX_ON);

**Comment by domzae** [comment] 2020-10-14 21:54
Thanks @DTuloJr, I've pushed both of those fixes! Let me know if it's working!

**Comment by Nazgul084** [comment] 2020-10-14 22:08
> Thanks @DTuloJr, I've pushed both of those fixes! Let me know if it's working!
@domzae I'll verify shortly.

**Comment by Nazgul084** [comment] 2020-10-14 22:16
@domzae I replaced my local copy with your code (with my changes merged) and noticed an issue locking/unlocking the frame. Don't know the root cause, yet. The good news, no LUA errors, though. Alllllmost there.

Edit: @domzae, issue on my end. Frame won't move if Tabs are hidden. So far, looks good. Should check for missing events now that 9.0 dropped, but the critical break seems fixed.

**Comment by professionaltart** [comment] 2020-10-15 07:15
Just testing it out now, and the latest merge looks like it's working for me.  It looks like the frame transparency/texture doesn't change properly anymore but that's not a surprised based on the new game code changes.

**Closed as completed** 2020-10-31 06:27 UTC
